#!/bin/bash

set -ex

DESKTOP_ENVIROMENT="/usr/bin/hyprland-session"
CHECK_GREETD=$(ls /etc/greetd/config-login.toml)

#Write this enviroment at boot to run Diplay manager

if [ $CHECK_GREETD ]; then
  /usr/bin/restore-greetd steamos
  systemctl reset-failed display-manager.service
  systemctl restart display-manager.service
  echo "Restarted ReGreet"
  sleep 2
  /usr/bin/restore-greetd desktop
else
  systemctl reset-failed display-manager.service
  systemctl restart display-manager.service
fi
