#!/bin/bash

set -ex

case "$1" in
  login)
    cp /etc/greetd/config-login.toml /etc/greetd/config.toml || true
    systemctl reset-failed display-manager.service
    systemctl restart display-manager.service
  ;;
  desktop)
    cp /etc/greetd/config-desktop.toml /etc/greetd/config.toml || true
    systemctl reset-failed display-manager.service
    systemctl restart display-manager.service
  ;;
  gamescope)
    cp /etc/greetd/config-deck.toml /etc/greetd/config.toml || true
    systemctl reset-failed display-manager.service
    systemctl restart display-manager.service
  ;;
  *) #Revert Steam UI to desktop mode
    cp /etc/greetd/config-desktop.toml /etc/greetd/config.toml || true
    systemctl reset-failed display-manager.service
    systemctl restart display-manager.service
    cp /etc/greetd/config-login.toml /etc/greetd/config.toml
  ;;  
esac
