#! /usr/bin/bash

set -e

die() { echo >&2 "!! $*"; exit 1; }

CONF_FILE="/etc/sddm.conf.d/03-gamescope-session.conf"
SENTINEL_FILE="steamos-session-select"

# For sanity this shipped file must be present, to ensure we're still on a normal-looking Chimeraos setup.
# The file was change to greetd config file
CHECK_FILE="/etc/greetd/config.toml"

session="${1:-gamescope}"
session_type="wayland"

session_launcher="gamescope-session"
create_sentinel=""

if [[ "$2" == "--sentinel-created" ]]; then
  SENTINEL_CREATED=1
  session_type="wayland"
fi

# Update config sentinel
if [[ -z $SENTINEL_CREATED ]]; then
  [[ $EUID == 0 ]] && die "Running $0 as root is not allowed"

  [[ -n ${HOME+x} ]] || die "No \$HOME variable"
  config_dir="${XDG_CONF_DIR:-"$HOME/.config"}"
  session_type=$(
    cd "$HOME"
    mkdir -p "$config_dir"
    cd "$config_dir"
    if [[ -f "steamos-session-type" ]]; then
      cp steamos-session-type "$SENTINEL_FILE"
    else
      echo "wayland" > "$SENTINEL_FILE"
    fi
    cat "$SENTINEL_FILE"
  )

  # clear steam game desktop shortcut clutter
  DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
  grep --files-with-matches "Exec=steam steam://rungameid/" ${DATA_HOME}/applications/* | tr '\n' '\0' | xargs -0 -I {} rm {} || true

  # If we were executed as a session user and then re-execute as root below, we don't want to set root's sentinel too
  export SENTINEL_CREATED=1
fi

# We use "plasma" as "desktop" to hook up to SteamOS's scripts
# Change the session_launcher for your command you use on greetd
case "$session" in
  plasma-wayland-persistent)
    session_launcher="hyprland.desktop"
  ;;
  plasma-x11-persistent)
    session_launcher="hyprland.desktop"
  ;;
  desktop|plasma)
    session_launcher="hyprland.desktop"
    create_sentinel=1
  ;;
  gamescope)
    session_launcher="gamescope-session.desktop"
    create_sentinel=1
  ;;
  login)     
    create_sentinel=1
    #will delete the autologin file bellow
  ;;
  *)
    echo >&2 "!! Unrecognized session '$session'"
    exit 1
  ;;
esac

echo "Updated user selected session to $session"

# Become root
if [[ $EUID != 0 ]]; then
  exec pkexec "$(realpath $0)" "$session" --sentinel-created
  exit 1
fi

if [[ "$session" = login ]]; then
	rm $CONF_FILE || die
	sleep 1
	exit 1
else
	# Update this to greetd format (pls edit for your user)
	{
  	echo "[Autologin]"
  	echo "Session=$session_launcher"
	} > "$CONF_FILE"
fi

echo "Updated system autologin session to $session"
systemctl reset-failed sddm
systemctl restart sddm
echo "Restarted SDDM Display Manager"

